included: # 린트 과정에 포함할 파일 경로. 이 항목이 존재하면 `--path`는 무시됨
  - lintTest
excluded: # 린트 과정에서 무시할 파일 경로. `included`보다 우선순위 높음
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
disabled_rules: #rules identifiers to exclude from running
  - line_length
  - control_statement
  - todo
identifier_name:
  allowed_symbols: "_"
  min_length: 3
