name: SwiftLint
on:
  pull_request:
    paths:
      - '.github/workflows/swift.yml'
jobs:
  echo:
     runs-on: macos-latest
     steps:
     - uses: actions/checkout@v1
     - name: testtesttest
     - run: echo Hello, World!
