name: SwiftLint
on:
  pull_request:
    paths:
      - '.github/workflows/swift.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
jobs:
  echo:
    runs-on: macos-latest
    steps:
      - name: Run SwiftLint
        run: swiftlint lint --path .swiftlint.yml
